version: '3.8'

volumes:
  postgres_data:
  static_folder:
  media_folder:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: kosteich/foodgram_web:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_folder:/code/static
      - media_folder:/code/media
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.5
    container_name: footgram_nginx
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_folder:/code/static
      - media_folder:/code/media
    ports:
      - "80:80"